export CONNECTION_STRING=MYSTRING

psql "$CONNECTION_STRING" -c "DROP SCHEMA public CASCADE;"
psql "$CONNECTION_STRING" -c "CREATE SCHEMA public;"
psql "$CONNECTION_STRING" -c "GRANT ALL ON SCHEMA public TO jwfbean;"
psql "$CONNECTION_STRING" -c "GRANT ALL ON SCHEMA public TO public;"
